LanguageCode = "pt-BR"
defaultContentLanguage = "pt-BR"
title = "Cadafalso"
baseURL = "https://guaracy.github.io/"
PygmentsCodeFences = true
PygmentsStyle = "default"
theme = "zgbm"
# greyshade
subscribe_rss = "/index.xml"
#googleAnalytics = "UA-92986383-1"

[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"

[Params]
Author = "Guaracy Monteiro"
subtitle = "Apenas mais um blog"
twitter = "guaracybm"
github = "guaracy"
facebook = "guaracybm"
contact = "mailto:guaracy.bm@gmail.com"
#themecolor = "#ff0000"
bio = "Apenas um programador esforçado."
ga_api_key = "UA-92986383-1"


#facebook_like = true
#twitter_tweet_button = true
#google_plus_one = "true"
#addthis_profile_id = ""